version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_operations
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pgrep", "-f", "mariadbd"]
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - DB_HOST=mariadb
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=crud_operations
    ports:
      - "5005:5005"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://nginx/api
    ports:
      - "3000:80"
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
