apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
spec:
  selector:
    app: nodejs-api
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 30090  # Exposing the service on port 30080
  type: NodePort
